version: '3.5'

services:
  railor:
    image: flgl/rails:5.2.2
    hostname: railor
    container_name: railor
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

