version: '3.5'

services:
  railor:
    image: flgl/rails:5.2.2
    hostname: railor
    container_name: railor
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: "development"
      THUMBOR_SECURITY_KEY: "${SECURITY_KEY}"
    tty: true
    stdin_open: true
  
  thumbor:
    image: flgl/thumbor:6.7.0
    hostname: thumbor
    container_name: thumbor
    environment:
      UPLOAD_ENABLED: "True"
      FILE_LOADER_ROOT_PATH: "/usr/local/thumbor/loader"
      SECURITY_KEY: "${SECURITY_KEY}"
    ports:
      - "8888:8888"

